packages:
  - 'components/*'
  - 'configs/*'
  - 'hooks/*'
  - 'libraries/*'

catalog:
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  '@vanilla-extract/css': ^1.16.1
  '@vanilla-extract/css-utils': ^0.1.4
  '@vanilla-extract/dynamic': ^2.1.2
  clsx: ^2.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
