packages:
  - 'components/*'
  - 'configs/*'
  - 'hooks/*'
  - 'libraries/*'

catalog:
  '@floating-ui/react': ^0.26.28
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  '@types/react-test-renderer': ^18.3.0
  '@types/react-transition-group': ^4.4.11
  '@vanilla-extract/css': ^1.16.1
  '@vanilla-extract/css-utils': ^0.1.4
  '@vanilla-extract/dynamic': ^2.1.2
  clsx: ^2.1.1
  happy-dom: ^20.0.0
  prettier: ^3.4.1
  react: ^18.3.1
  react-dom: ^18.3.1
  react-test-renderer: ^18.3.1
  react-transition-group: ^4.4.5
  typescript: ^5.7.2
  vitest: ^2.1.9
