packages:
  - components/*
  - configs/*
  - hooks/*
  - libraries/*

catalog:
  '@floating-ui/react': ^0.27.19
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.1
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/react-transition-group': ^4.4.12
  '@vanilla-extract/css': ^1.20.1
  '@vanilla-extract/css-utils': ^0.1.6
  '@vanilla-extract/dynamic': ^2.1.5
  clsx: ^2.1.1
  happy-dom: ^20.9.0
  prettier: ^3.8.3
  react: ^19.2.5
  react-dom: ^19.2.5
  react-transition-group: ^4.4.5
  typescript: ^6.0.3
  vitest: ^4.1.5
