packages:
  - 'components/*'
  - 'configs/*'
  - 'hooks/*'
  - 'libraries/*'

catalog:
  '@floating-ui/react': ^0.26.28
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  '@types/react-transition-group': ^4.4.11
  '@vanilla-extract/css': ^1.16.1
  '@vanilla-extract/css-utils': ^0.1.4
  '@vanilla-extract/dynamic': ^2.1.2
  clsx: ^2.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
  react-transition-group: ^4.4.5
  typescript: ^5.7.2
