import { ReactComponent as UiAddGPTColumnLIconInner } from './addGPTColumn/addGPTColumn.large.svg';
import { ReactComponent as UiAddNewColumnLIconInner } from './addNewColumn/addNewColumn.large.svg';
import { ReactComponent as UiApiColumnLIconInner } from './apiColumn/apiColumn.large.svg';
import { ReactComponent as UiApiTableLIconInner } from './apiTable/apiTable.large.svg';
import { ReactComponent as UiBlankTableLIconInner } from './blankTable/blankTable.large.svg';
import { ReactComponent as UiByExampleLIconInner } from './byExample/byExample.large.svg';
import { ReactComponent as UiChangeDataTypeLIconInner } from './changeDataType/changeDataType.large.svg';
import { ReactComponent as UiChartLIconInner } from './chart/chart.large.svg';
import { ReactComponent as UiCleanLIconInner } from './clean/clean.large.svg';
import { ReactComponent as UiConditionLIconInner } from './condition/condition.large.svg';
import { ReactComponent as UiCountMatchesLIconInner } from './countMatches/countMatches.large.svg';
import { ReactComponent as UiCrossJoinLIconInner } from './crossJoin/crossJoin.large.svg';
import { ReactComponent as UiCsvFileLIconInner } from './csvFile/csvFile.large.svg';
import { ReactComponent as UiCsvOutputLIconInner } from './csvOutput/csvOutput.large.svg';
import { ReactComponent as UiEditColumnLIconInner } from './editColumn/editColumn.large.svg';
import { ReactComponent as UiEnrichmentLIconInner } from './enrichment/enrichment.large.svg';
import { ReactComponent as UiEnrichmentApolloLIconInner } from './enrichmentApollo/enrichmentApollo.large.svg';
import { ReactComponent as UiEnrichmentClearbitLIconInner } from './enrichmentClearbit/enrichmentClearbit.large.svg';
import { ReactComponent as UiEnrichmentContactOutLIconInner } from './enrichmentContactOut/enrichmentContactOut.large.svg';
import { ReactComponent as UiEnrichmentFindymailLIconInner } from './enrichmentFindymail/enrichmentFindymail.large.svg';
import { ReactComponent as UiEnrichmentHunterLIconInner } from './enrichmentHunter/enrichmentHunter.large.svg';
import { ReactComponent as UiEnrichmentLead411LIconInner } from './enrichmentLead411/enrichmentLead411.large.svg';
import { ReactComponent as UiEnrichmentLeadMagicLIconInner } from './enrichmentLeadMagic/enrichmentLeadMagic.large.svg';
import { ReactComponent as UiEnrichmentLeadReachLIconInner } from './enrichmentLeadReach/enrichmentLeadReach.large.svg';
import { ReactComponent as UiEnrichmentPeopleDataLabsLIconInner } from './enrichmentPeopleDataLabs/enrichmentPeopleDataLabs.large.svg';
import { ReactComponent as UiEnrichmentPredictLeadsLIconInner } from './enrichmentPredictLeads/enrichmentPredictLeads.large.svg';
import { ReactComponent as UiEnrichmentProspeoLIconInner } from './enrichmentProspeo/enrichmentProspeo.large.svg';
import { ReactComponent as UiEnrichmentReverseContactLIconInner } from './enrichmentReverseContact/enrichmentReverseContact.large.svg';
import { ReactComponent as UiEnrichmentSignalHireLIconInner } from './enrichmentSignalHire/enrichmentSignalHire.large.svg';
import { ReactComponent as UiEnrichmentUpLeadLIconInner } from './enrichmentUpLead/enrichmentUpLead.large.svg';
import { ReactComponent as UiEnrichmentZoomInfoLIconInner } from './enrichmentZoomInfo/enrichmentZoomInfo.large.svg';
import { ReactComponent as UiExtractLIconInner } from './extract/extract.large.svg';
import { ReactComponent as UiFilterLIconInner } from './filter/filter.large.svg';
import { ReactComponent as UiFolderSourceLIconInner } from './folderSource/folderSource.large.svg';
import { ReactComponent as UiGoldenLIconInner } from './golden/golden.large.svg';
import { ReactComponent as UiGPTNodeLIconInner } from './gptNode/gptNode.large.svg';
import { ReactComponent as UiGroupLIconInner } from './group/group.large.svg';
import { ReactComponent as UiGroupByLIconInner } from './groupBy/groupBy.large.svg';
import { ReactComponent as UiInnerJoinLIconInner } from './innerJoin/innerJoin.large.svg';
import { ReactComponent as UiJsonFileLIconInner } from './jsonFile/jsonFile.large.svg';
import { ReactComponent as UiLeftJoinLIconInner } from './leftJoin/leftJoin.large.svg';
import { ReactComponent as UiLocalFileLIconInner } from './localFile/localFile.large.svg';
import { ReactComponent as UiLocalOutputLIconInner } from './localOutput/localOutput.large.svg';
import { ReactComponent as UiMergeColumnsLIconInner } from './mergeColumns/mergeColumns.large.svg';
import { ReactComponent as UiMultiSourceLIconInner } from './multiSource/multiSource.large.svg';
import { ReactComponent as UiNestLIconInner } from './nest/nest.large.svg';
import { ReactComponent as UiNoNodeLIconInner } from './noNode/noNode.large.svg';
import { ReactComponent as UiOuterJoinLIconInner } from './outerJoin/outerJoin.large.svg';
import { ReactComponent as UiOutputLIconInner } from './output/output.large.svg';
import { ReactComponent as UiPivotLIconInner } from './pivot/pivot.large.svg';
import { ReactComponent as UiPostgresOutputLIconInner } from './postgresOutput/postgresOutput.large.svg';
import { ReactComponent as UiPostgresSourceLIconInner } from './postgresSource/postgresSource.large.svg';
import { ReactComponent as UiPostgresSqlLIconInner } from './postgresSql/postgresSql.large.svg';
import { ReactComponent as UiRemoveDuplicateRowsLIconInner } from './removeDuplicateRows/removeDuplicateRows.large.svg';
import { ReactComponent as UiReplaceLIconInner } from './replace/replace.large.svg';
import { ReactComponent as UiReportLIconInner } from './report/report.large.svg';
import { ReactComponent as UiRightJoinLIconInner } from './rightJoin/rightJoin.large.svg';
import { ReactComponent as UiSearchLIconInner } from './search/search.large.svg';
import { ReactComponent as UiSearchCompanyLIconInner } from './searchCompany/searchCompany.large.svg';
import { ReactComponent as UiSearchDeveloperLIconInner } from './searchDeveloper/searchDeveloper.large.svg';
import { ReactComponent as UiSearchLookalikeCompanyLIconInner } from './searchLookalikeCompany/searchLookalikeCompany.large.svg';
import { ReactComponent as UiSearchPeopleLIconInner } from './searchPeople/searchPeople.large.svg';
import { ReactComponent as UiSnowflakeOutputLIconInner } from './snowflakeOutput/snowflakeOutput.large.svg';
import { ReactComponent as UiSnowflakeSourceLIconInner } from './snowflakeSource/snowflakeSource.large.svg';
import { ReactComponent as UiSortByAscendingLIconInner } from './sortByAscending/sortByAscending.large.svg';
import { ReactComponent as UiSortByDescendingLIconInner } from './sortByDescending/sortByDescending.large.svg';
import { ReactComponent as UiSourceLIconInner } from './source/source.large.svg';
import { ReactComponent as UiSplitColumnsLIconInner } from './splitColumns/splitColumns.large.svg';
import { ReactComponent as UiSqlLIconInner } from './sql/sql.large.svg';
import { ReactComponent as UiStandardizeLIconInner } from './standardize/standardize.large.svg';
import { ReactComponent as UiTabulaDriveLIconInner } from './tabulaDrive/tabulaDrive.large.svg';
import { ReactComponent as UiTomatDriveLIconInner } from './tomatDrive/tomatDrive.large.svg';
import { ReactComponent as UiTransposeLIconInner } from './transpose/transpose.large.svg';
import { ReactComponent as UiUnionLIconInner } from './union/union.large.svg';
import { ReactComponent as UiUnnestLIconInner } from './unnest/unnest.large.svg';
import { ReactComponent as UiUnpivotLIconInner } from './unpivot/unpivot.large.svg';
import { ReactComponent as UiWinFuncLIconInner } from './winFunc/winFunc.large.svg';
import { ReactComponent as UiXlsFileLIconInner } from './xlsFile/xlsFile.large.svg';
import { ReactComponent as UiXlsOutputLIconInner } from './xlsOutput/xlsOutput.large.svg';

import { icon } from './style.css';

import { createIcon } from './utils';

export const UiAddGPTColumnLIcon = createIcon(UiAddGPTColumnLIconInner, icon);
export const UiAddNewColumnLIcon = createIcon(UiAddNewColumnLIconInner, icon);
export const UiApiColumnLIcon = createIcon(UiApiColumnLIconInner, icon);
export const UiApiTableLIcon = createIcon(UiApiTableLIconInner, icon);
export const UiBlankTableLIcon = createIcon(UiBlankTableLIconInner, icon);
export const UiByExampleLIcon = createIcon(UiByExampleLIconInner, icon);
export const UiChangeDataTypeLIcon = createIcon(UiChangeDataTypeLIconInner, icon);
export const UiChartLIcon = createIcon(UiChartLIconInner, icon);
export const UiCleanLIcon = createIcon(UiCleanLIconInner, icon);
export const UiConditionLIcon = createIcon(UiConditionLIconInner, icon);
export const UiCountMatchesLIcon = createIcon(UiCountMatchesLIconInner, icon);
export const UiCrossJoinLIcon = createIcon(UiCrossJoinLIconInner, icon);
export const UiCsvFileLIcon = createIcon(UiCsvFileLIconInner, icon);
export const UiCsvOutputLIcon = createIcon(UiCsvOutputLIconInner, icon);
export const UiEditColumnLIcon = createIcon(UiEditColumnLIconInner, icon);
export const UiEnrichmentLIcon = createIcon(UiEnrichmentLIconInner, icon);
export const UiEnrichmentApolloLIcon = createIcon(UiEnrichmentApolloLIconInner, icon);
export const UiEnrichmentClearbitLIcon = createIcon(UiEnrichmentClearbitLIconInner, icon);
export const UiEnrichmentContactOutLIcon = createIcon(UiEnrichmentContactOutLIconInner, icon);
export const UiEnrichmentFindymailLIcon = createIcon(UiEnrichmentFindymailLIconInner, icon);
export const UiEnrichmentHunterLIcon = createIcon(UiEnrichmentHunterLIconInner, icon);
export const UiEnrichmentLead411LIcon = createIcon(UiEnrichmentLead411LIconInner, icon);
export const UiEnrichmentLeadMagicLIcon = createIcon(UiEnrichmentLeadMagicLIconInner, icon);
export const UiEnrichmentLeadReachLIcon = createIcon(UiEnrichmentLeadReachLIconInner, icon);
export const UiEnrichmentPeopleDataLabsLIcon = createIcon(
  UiEnrichmentPeopleDataLabsLIconInner,
  icon,
);
export const UiEnrichmentPredictLeadsLIcon = createIcon(UiEnrichmentPredictLeadsLIconInner, icon);
export const UiEnrichmentProspeoLIcon = createIcon(UiEnrichmentProspeoLIconInner, icon);
export const UiEnrichmentReverseContactLIcon = createIcon(
  UiEnrichmentReverseContactLIconInner,
  icon,
);
export const UiEnrichmentSignalHireLIcon = createIcon(UiEnrichmentSignalHireLIconInner, icon);
export const UiEnrichmentUpLeadLIcon = createIcon(UiEnrichmentUpLeadLIconInner, icon);
export const UiEnrichmentZoomInfoLIcon = createIcon(UiEnrichmentZoomInfoLIconInner, icon);
export const UiExtractLIcon = createIcon(UiExtractLIconInner, icon);
export const UiFilterLIcon = createIcon(UiFilterLIconInner, icon);
export const UiFolderSourceLIcon = createIcon(UiFolderSourceLIconInner, icon);
export const UiGoldenLIcon = createIcon(UiGoldenLIconInner, icon);
export const UiGPTNodeLIcon = createIcon(UiGPTNodeLIconInner, icon);
export const UiGroupLIcon = createIcon(UiGroupLIconInner, icon);
export const UiGroupByLIcon = createIcon(UiGroupByLIconInner, icon);
export const UiInnerJoinLIcon = createIcon(UiInnerJoinLIconInner, icon);
export const UiJsonFileLIcon = createIcon(UiJsonFileLIconInner, icon);
export const UiLeftJoinLIcon = createIcon(UiLeftJoinLIconInner, icon);
export const UiLocalFileLIcon = createIcon(UiLocalFileLIconInner, icon);
export const UiLocalOutputLIcon = createIcon(UiLocalOutputLIconInner, icon);
export const UiMergeColumnsLIcon = createIcon(UiMergeColumnsLIconInner, icon);
export const UiMultiSourceLIcon = createIcon(UiMultiSourceLIconInner, icon);
export const UiNestLIcon = createIcon(UiNestLIconInner, icon);
export const UiNoNodeLIcon = createIcon(UiNoNodeLIconInner, icon);
export const UiOuterJoinLIcon = createIcon(UiOuterJoinLIconInner, icon);
export const UiOutputLIcon = createIcon(UiOutputLIconInner, icon);
export const UiPivotLIcon = createIcon(UiPivotLIconInner, icon);
export const UiPostgresOutputLIcon = createIcon(UiPostgresOutputLIconInner, icon);
export const UiPostgresSourceLIcon = createIcon(UiPostgresSourceLIconInner, icon);
export const UiPostgresSqlLIcon = createIcon(UiPostgresSqlLIconInner, icon);
export const UiRemoveDuplicateRowsLIcon = createIcon(UiRemoveDuplicateRowsLIconInner, icon);
export const UiReplaceLIcon = createIcon(UiReplaceLIconInner, icon);
export const UiReportLIcon = createIcon(UiReportLIconInner, icon);
export const UiRightJoinLIcon = createIcon(UiRightJoinLIconInner, icon);
export const UiSearchLIcon = createIcon(UiSearchLIconInner, icon);
export const UiSearchCompanyLIcon = createIcon(UiSearchCompanyLIconInner, icon);
export const UiSearchDeveloperLIcon = createIcon(UiSearchDeveloperLIconInner, icon);
export const UiSearchLookalikeCompanyLIcon = createIcon(UiSearchLookalikeCompanyLIconInner, icon);
export const UiSearchPeopleLIcon = createIcon(UiSearchPeopleLIconInner, icon);
export const UiSnowflakeOutputLIcon = createIcon(UiSnowflakeOutputLIconInner, icon);
export const UiSnowflakeSourceLIcon = createIcon(UiSnowflakeSourceLIconInner, icon);
export const UiSortByAscendingLIcon = createIcon(UiSortByAscendingLIconInner, icon);
export const UiSortByDescendingLIcon = createIcon(UiSortByDescendingLIconInner, icon);
export const UiSourceLIcon = createIcon(UiSourceLIconInner, icon);
export const UiSplitColumnsLIcon = createIcon(UiSplitColumnsLIconInner, icon);
export const UiSqlLIcon = createIcon(UiSqlLIconInner, icon);
export const UiStandardizeLIcon = createIcon(UiStandardizeLIconInner, icon);
export const UiTabulaDriveLIcon = createIcon(UiTabulaDriveLIconInner, icon);
export const UiTomatDriveLIcon = createIcon(UiTomatDriveLIconInner, icon);
export const UiTransposeLIcon = createIcon(UiTransposeLIconInner, icon);
export const UiUnionLIcon = createIcon(UiUnionLIconInner, icon);
export const UiUnnestLIcon = createIcon(UiUnnestLIconInner, icon);
export const UiUnpivotLIcon = createIcon(UiUnpivotLIconInner, icon);
export const UiWinFuncLIcon = createIcon(UiWinFuncLIconInner, icon);
export const UiXlsFileLIcon = createIcon(UiXlsFileLIconInner, icon);
export const UiXlsOutputLIcon = createIcon(UiXlsOutputLIconInner, icon);
