import { ReactComponent as UiAddGPTColumnMIconInner } from './addGPTColumn/addGPTColumn.medium.svg';
import { ReactComponent as UiAddNewColumnMIconInner } from './addNewColumn/addNewColumn.medium.svg';
import { ReactComponent as UiApiColumnMIconInner } from './apiColumn/apiColumn.medium.svg';
import { ReactComponent as UiBlankTableMIconInner } from './blankTable/blankTable.medium.svg';
import { ReactComponent as UiByExampleMIconInner } from './byExample/byExample.medium.svg';
import { ReactComponent as UiChangeDataTypeMIconInner } from './changeDataType/changeDataType.medium.svg';
import { ReactComponent as UiChartMIconInner } from './chart/chart.medium.svg';
import { ReactComponent as UiCleanMIconInner } from './clean/clean.medium.svg';
import { ReactComponent as UiConditionMIconInner } from './condition/condition.medium.svg';
import { ReactComponent as UiCountMatchesMIconInner } from './countMatches/countMatches.medium.svg';
import { ReactComponent as UiCrossJoinMIconInner } from './crossJoin/crossJoin.medium.svg';
import { ReactComponent as UiCsvFileMIconInner } from './csvFile/csvFile.medium.svg';
import { ReactComponent as UiCsvOutputMIconInner } from './csvOutput/csvOutput.medium.svg';
import { ReactComponent as UiEditColumnMIconInner } from './editColumn/editColumn.medium.svg';
import { ReactComponent as UiEnrichmentMIconInner } from './enrichment/enrichment.medium.svg';
import { ReactComponent as UiEnrichmentApolloMIconInner } from './enrichmentApollo/enrichmentApollo.medium.svg';
import { ReactComponent as UiEnrichmentClearbitMIconInner } from './enrichmentClearbit/enrichmentClearbit.medium.svg';
import { ReactComponent as UiEnrichmentContactOutMIconInner } from './enrichmentContactOut/enrichmentContactOut.medium.svg';
import { ReactComponent as UiEnrichmentLead411MIconInner } from './enrichmentLead411/enrichmentLead411.medium.svg';
import { ReactComponent as UiEnrichmentLeadReachMIconInner } from './enrichmentLeadReach/enrichmentLeadReach.medium.svg';
import { ReactComponent as UiEnrichmentPeopleDataLabsMIconInner } from './enrichmentPeopleDataLabs/enrichmentPeopleDataLabs.medium.svg';
import { ReactComponent as UiEnrichmentReverseContactMIconInner } from './enrichmentReverseContact/enrichmentReverseContact.medium.svg';
import { ReactComponent as UiEnrichmentSignalHireMIconInner } from './enrichmentSignalHire/enrichmentSignalHire.medium.svg';
import { ReactComponent as UiEnrichmentZoomInfoMIconInner } from './enrichmentZoomInfo/enrichmentZoomInfo.medium.svg';
import { ReactComponent as UiExtractMIconInner } from './extract/extract.medium.svg';
import { ReactComponent as UiFilterMIconInner } from './filter/filter.medium.svg';
import { ReactComponent as UiFolderSourceMIconInner } from './folderSource/folderSource.medium.svg';
import { ReactComponent as UiGoldenMIconInner } from './golden/golden.medium.svg';
import { ReactComponent as UiGPTNodeMIconInner } from './gptNode/gptNode.medium.svg';
import { ReactComponent as UiGroupMIconInner } from './group/group.medium.svg';
import { ReactComponent as UiGroupByMIconInner } from './groupBy/groupBy.medium.svg';
import { ReactComponent as UiInnerJoinMIconInner } from './innerJoin/innerJoin.medium.svg';
import { ReactComponent as UiJsonFileMIconInner } from './jsonFile/jsonFile.medium.svg';
import { ReactComponent as UiLeftJoinMIconInner } from './leftJoin/leftJoin.medium.svg';
import { ReactComponent as UiLocalFileMIconInner } from './localFile/localFile.medium.svg';
import { ReactComponent as UiLocalOutputMIconInner } from './localOutput/localOutput.medium.svg';
import { ReactComponent as UiMergeColumnsMIconInner } from './mergeColumns/mergeColumns.medium.svg';
import { ReactComponent as UiMultiSourceMIconInner } from './multiSource/multiSource.medium.svg';
import { ReactComponent as UiNestMIconInner } from './nest/nest.medium.svg';
import { ReactComponent as UiNewBlankTableMIconInner } from './newBlankTable/newBlankTable.medium.svg';
import { ReactComponent as UiNewChartMIconInner } from './newChart/newChart.medium.svg';
import { ReactComponent as UiOuterJoinMIconInner } from './outerJoin/outerJoin.medium.svg';
import { ReactComponent as UiOutputMIconInner } from './output/output.medium.svg';
import { ReactComponent as UiPivotMIconInner } from './pivot/pivot.medium.svg';
import { ReactComponent as UiPostgresOutputMIconInner } from './postgresOutput/postgresOutput.medium.svg';
import { ReactComponent as UiPostgresSourceMIconInner } from './postgresSource/postgresSource.medium.svg';
import { ReactComponent as UiRecipeMIconInner } from './recipe/recipe.medium.svg';
import { ReactComponent as UiRemoveDuplicateRowsMIconInner } from './removeDuplicateRows/removeDuplicateRows.medium.svg';
import { ReactComponent as UiReplaceMIconInner } from './replace/replace.medium.svg';
import { ReactComponent as UiReportMIconInner } from './report/report.medium.svg';
import { ReactComponent as UiRightJoinMIconInner } from './rightJoin/rightJoin.medium.svg';
import { ReactComponent as UiSnowflakeOutputMIconInner } from './snowflakeOutput/snowflakeOutput.medium.svg';
import { ReactComponent as UiSnowflakeSourceMIconInner } from './snowflakeSource/snowflakeSource.medium.svg';
import { ReactComponent as UiSortByAscendingMIconInner } from './sortByAscending/sortByAscending.medium.svg';
import { ReactComponent as UiSortByDescendingMIconInner } from './sortByDescending/sortByDescending.medium.svg';
import { ReactComponent as UiSourceMIconInner } from './source/source.medium.svg';
import { ReactComponent as UiSplitColumnsMIconInner } from './splitColumns/splitColumns.medium.svg';
import { ReactComponent as UiSqlMIconInner } from './sql/sql.medium.svg';
import { ReactComponent as UiStandardizeMIconInner } from './standardize/standardize.medium.svg';
import { ReactComponent as UiTabulaDriveMIconInner } from './tabulaDrive/tabulaDrive.medium.svg';
import { ReactComponent as UiTomatDriveMIconInner } from './tomatDrive/tomatDrive.medium.svg';
import { ReactComponent as UiTransposeMIconInner } from './transpose/transpose.medium.svg';
import { ReactComponent as UiUnionMIconInner } from './union/union.medium.svg';
import { ReactComponent as UiUnnestMIconInner } from './unnest/unnest.medium.svg';
import { ReactComponent as UiUnpivotMIconInner } from './unpivot/unpivot.medium.svg';
import { ReactComponent as UiWinFuncMIconInner } from './winFunc/winFunc.medium.svg';
import { ReactComponent as UiXlsFileMIconInner } from './xlsFile/xlsFile.medium.svg';
import { ReactComponent as UiXlsOutputMIconInner } from './xlsOutput/xlsOutput.medium.svg';

import { icon } from './style.css';

import { createIcon } from './utils';

export const UiAddGPTColumnMIcon = createIcon(UiAddGPTColumnMIconInner, icon);
export const UiAddNewColumnMIcon = createIcon(UiAddNewColumnMIconInner, icon);
export const UiApiColumnMIcon = createIcon(UiApiColumnMIconInner, icon);
export const UiBlankTableMIcon = createIcon(UiBlankTableMIconInner, icon);
export const UiByExampleMIcon = createIcon(UiByExampleMIconInner, icon);
export const UiChangeDataTypeMIcon = createIcon(UiChangeDataTypeMIconInner, icon);
export const UiChartMIcon = createIcon(UiChartMIconInner, icon);
export const UiCleanMIcon = createIcon(UiCleanMIconInner, icon);
export const UiConditionMIcon = createIcon(UiConditionMIconInner, icon);
export const UiCountMatchesMIcon = createIcon(UiCountMatchesMIconInner, icon);
export const UiCrossJoinMIcon = createIcon(UiCrossJoinMIconInner, icon);
export const UiCsvFileMIcon = createIcon(UiCsvFileMIconInner, icon);
export const UiCsvOutputMIcon = createIcon(UiCsvOutputMIconInner, icon);
export const UiEditColumnMIcon = createIcon(UiEditColumnMIconInner, icon);
export const UiEnrichmentMIcon = createIcon(UiEnrichmentMIconInner, icon);
export const UiEnrichmentApolloMIcon = createIcon(UiEnrichmentApolloMIconInner, icon);
export const UiEnrichmentClearbitMIcon = createIcon(UiEnrichmentClearbitMIconInner, icon);
export const UiEnrichmentContactOutMIcon = createIcon(UiEnrichmentContactOutMIconInner, icon);
export const UiEnrichmentLead411MIcon = createIcon(UiEnrichmentLead411MIconInner, icon);
export const UiEnrichmentLeadReachMIcon = createIcon(UiEnrichmentLeadReachMIconInner, icon);
export const UiEnrichmentPeopleDataLabsMIcon = createIcon(
  UiEnrichmentPeopleDataLabsMIconInner,
  icon,
);
export const UiEnrichmentReverseContactMIcon = createIcon(
  UiEnrichmentReverseContactMIconInner,
  icon,
);
export const UiEnrichmentSignalHireMIcon = createIcon(UiEnrichmentSignalHireMIconInner, icon);
export const UiEnrichmentZoomInfoMIcon = createIcon(UiEnrichmentZoomInfoMIconInner, icon);
export const UiExtractMIcon = createIcon(UiExtractMIconInner, icon);
export const UiFilterMIcon = createIcon(UiFilterMIconInner, icon);
export const UiFolderSourceMIcon = createIcon(UiFolderSourceMIconInner, icon);
export const UiGoldenMIcon = createIcon(UiGoldenMIconInner, icon);
export const UiGPTNodeMIcon = createIcon(UiGPTNodeMIconInner, icon);
export const UiGroupMIcon = createIcon(UiGroupMIconInner, icon);
export const UiGroupByMIcon = createIcon(UiGroupByMIconInner, icon);
export const UiInnerJoinMIcon = createIcon(UiInnerJoinMIconInner, icon);
export const UiJsonFileMIcon = createIcon(UiJsonFileMIconInner, icon);
export const UiLeftJoinMIcon = createIcon(UiLeftJoinMIconInner, icon);
export const UiLocalFileMIcon = createIcon(UiLocalFileMIconInner, icon);
export const UiLocalOutputMIcon = createIcon(UiLocalOutputMIconInner, icon);
export const UiMergeColumnsMIcon = createIcon(UiMergeColumnsMIconInner, icon);
export const UiMultiSourceMIcon = createIcon(UiMultiSourceMIconInner, icon);
export const UiNestMIcon = createIcon(UiNestMIconInner, icon);
export const UiNewBlankTableMIcon = createIcon(UiNewBlankTableMIconInner, icon);
export const UiNewChartMIcon = createIcon(UiNewChartMIconInner, icon);
export const UiOuterJoinMIcon = createIcon(UiOuterJoinMIconInner, icon);
export const UiOutputMIcon = createIcon(UiOutputMIconInner, icon);
export const UiPivotMIcon = createIcon(UiPivotMIconInner, icon);
export const UiPostgresOutputMIcon = createIcon(UiPostgresOutputMIconInner, icon);
export const UiPostgresSourceMIcon = createIcon(UiPostgresSourceMIconInner, icon);
export const UiRecipeMIcon = createIcon(UiRecipeMIconInner, icon);
export const UiRemoveDuplicateRowsMIcon = createIcon(UiRemoveDuplicateRowsMIconInner, icon);
export const UiReplaceMIcon = createIcon(UiReplaceMIconInner, icon);
export const UiReportMIcon = createIcon(UiReportMIconInner, icon);
export const UiRightJoinMIcon = createIcon(UiRightJoinMIconInner, icon);
export const UiSnowflakeOutputMIcon = createIcon(UiSnowflakeOutputMIconInner, icon);
export const UiSnowflakeSourceMIcon = createIcon(UiSnowflakeSourceMIconInner, icon);
export const UiSortByAscendingMIcon = createIcon(UiSortByAscendingMIconInner, icon);
export const UiSortByDescendingMIcon = createIcon(UiSortByDescendingMIconInner, icon);
export const UiSourceMIcon = createIcon(UiSourceMIconInner, icon);
export const UiSplitColumnsMIcon = createIcon(UiSplitColumnsMIconInner, icon);
export const UiSqlMIcon = createIcon(UiSqlMIconInner, icon);
export const UiStandardizeMIcon = createIcon(UiStandardizeMIconInner, icon);
export const UiTabulaDriveMIcon = createIcon(UiTabulaDriveMIconInner, icon);
export const UiTomatDriveMIcon = createIcon(UiTomatDriveMIconInner, icon);
export const UiTransposeMIcon = createIcon(UiTransposeMIconInner, icon);
export const UiUnionMIcon = createIcon(UiUnionMIconInner, icon);
export const UiUnnestMIcon = createIcon(UiUnnestMIconInner, icon);
export const UiUnpivotMIcon = createIcon(UiUnpivotMIconInner, icon);
export const UiWinFuncMIcon = createIcon(UiWinFuncMIconInner, icon);
export const UiXlsFileMIcon = createIcon(UiXlsFileMIconInner, icon);
export const UiXlsOutputMIcon = createIcon(UiXlsOutputMIconInner, icon);
