import { ReactComponent as UiFolderSourceSIconInner } from './folderSource/folderSource.small.svg';
import { ReactComponent as UiLocalFileSIconInner } from './localFile/localFile.small.svg';
import { ReactComponent as UiPostgresSourceSIconInner } from './postgresSource/postgresSource.small.svg';
import { ReactComponent as UiReportSIconInner } from './report/report.small.svg';
import { ReactComponent as UiSnowflakeSourceSIconInner } from './snowflakeSource/snowflakeSource.small.svg';

import { icon } from './style.css';

import { createIcon } from './utils';

export const UiFolderSourceSIcon = createIcon(UiFolderSourceSIconInner, icon);
export const UiLocalFileSIcon = createIcon(UiLocalFileSIconInner, icon);
export const UiPostgresSourceSIcon = createIcon(UiPostgresSourceSIconInner, icon);
export const UiReportSIcon = createIcon(UiReportSIconInner, icon);
export const UiSnowflakeSourceSIcon = createIcon(UiSnowflakeSourceSIconInner, icon);

export { ReactComponent as UiAddGPTColumnSIcon } from './addGPTColumn/addGPTColumn.small.svg';
export { ReactComponent as UiAddNewColumnSIcon } from './addNewColumn/addNewColumn.small.svg';
export { ReactComponent as UiApiColumnSIcon } from './apiColumn/apiColumn.small.svg';
export { ReactComponent as UiApiTableSIcon } from './apiTable/apiTable.small.svg';
export { ReactComponent as UiBlankTableSIcon } from './blankTable/blankTable.small.svg';
export { ReactComponent as UiByExampleSIcon } from './byExample/byExample.small.svg';
export { ReactComponent as UiChangeDataTypeSIcon } from './changeDataType/changeDataType.small.svg';
export { ReactComponent as UiChartSIcon } from './chart/chart.small.svg';
export { ReactComponent as UiCleanSIcon } from './clean/clean.small.svg';
export { ReactComponent as UiConditionSIcon } from './condition/condition.small.svg';
export { ReactComponent as UiCountMatchesSIcon } from './countMatches/countMatches.small.svg';
export { ReactComponent as UiCrossJoinSIcon } from './crossJoin/crossJoin.small.svg';
export { ReactComponent as UiCsvFileSIcon } from './csvFile/csvFile.small.svg';
export { ReactComponent as UiEditColumnSIcon } from './editColumn/editColumn.small.svg';
export { ReactComponent as UiEnrichmentSIcon } from './enrichment/enrichment.small.svg';
export { ReactComponent as UiExtractSIcon } from './extract/extract.small.svg';
export { ReactComponent as UiFilterSIcon } from './filter/filter.small.svg';
export { ReactComponent as UiGPTNodeSIcon } from './gptNode/gptNode.small.svg';
export { ReactComponent as UiGroupBySIcon } from './groupBy/groupBy.small.svg';
export { ReactComponent as UiInnerJoinSIcon } from './innerJoin/innerJoin.small.svg';
export { ReactComponent as UiJsonFileSIcon } from './jsonFile/jsonFile.small.svg';
export { ReactComponent as UiLeftJoinSIcon } from './leftJoin/leftJoin.small.svg';
export { ReactComponent as UiMergeColumnsSIcon } from './mergeColumns/mergeColumns.small.svg';
export { ReactComponent as UiNestSIcon } from './nest/nest.small.svg';
export { ReactComponent as UiOuterJoinSIcon } from './outerJoin/outerJoin.small.svg';
export { ReactComponent as UiOutputSIcon } from './output/output.small.svg';
export { ReactComponent as UiPivotSIcon } from './pivot/pivot.small.svg';
export { ReactComponent as UiRecipeSIcon } from './recipe/recipe.small.svg';
export { ReactComponent as UiRemoveDuplicateRowsSIcon } from './removeDuplicateRows/removeDuplicateRows.small.svg';
export { ReactComponent as UiReplaceSIcon } from './replace/replace.small.svg';
export { ReactComponent as UiRightJoinSIcon } from './rightJoin/rightJoin.small.svg';
export { ReactComponent as UiSnowflakeSourceSIcon } from './snowflakeSource/snowflakeSource.small.svg';
export { ReactComponent as UiSortByAscendingSIcon } from './sortByAscending/sortByAscending.small.svg';
export { ReactComponent as UiSortByDescendingSIcon } from './sortByDescending/sortByDescending.small.svg';
export { ReactComponent as UiSourceSIcon } from './source/source.small.svg';
export { ReactComponent as UiSplitColumnsSIcon } from './splitColumns/splitColumns.small.svg';
export { ReactComponent as UiSqlSIcon } from './sql/sql.small.svg';
export { ReactComponent as UiStandardizeSIcon } from './standardize/standardize.small.svg';
export { ReactComponent as UiTransposeSIcon } from './transpose/transpose.small.svg';
export { ReactComponent as UiUnionSIcon } from './union/union.small.svg';
export { ReactComponent as UiUnnestSIcon } from './unnest/unnest.small.svg';
export { ReactComponent as UiUnpivotSIcon } from './unpivot/unpivot.small.svg';
export { ReactComponent as UiWinFuncSIcon } from './winFunc/winFunc.small.svg';
export { ReactComponent as UiXlsFileSIcon } from './xlsFile/xlsFile.small.svg';
