name: 'Check source code quality'
description: 'Runs build, linters and tests'

runs:
  using: composite

  steps:
    - name: Install packages
      shell: bash
      run: pnpm install

    - name: Build
      shell: bash
      run: pnpm build

    - name: Configure ESLint cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/eslint
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml', '.eslintrc.json', '.eslintignore') }}

    - name: Lint
      shell: bash
      run: pnpm lint --cache --cache-strategy content --cache-location ~/.cache/eslint

    - name: Test
      shell: bash
      run: pnpm test
