name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'ReTable/ui-kit'

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: ./.github/composite-actions/install-node

      - name: Check quality
        uses: ./.github/composite-actions/quality

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changesets): release new versions'
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish docs
        if: steps.changesets.outputs.published == 'true'
        run: gh workflow run docs.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
